# Generated by Django 4.2.14 on 2024-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord', models.CharField(max_length=120, verbose_name='Landlord Name')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=15, verbose_name='Zip Code')),
                ('date', models.DateField(verbose_name='Date lived')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('tenants', models.ManyToManyField(blank=True, to='properties.tenant')),
            ],
        ),
    ]
